### ISSUE TITLE
Directional light

### ISSUE THREAD

**Issue by sg3des** [tbogdala/fizzle#4]
How to create directional light? 

In your example [lights-forward](https://github.com/tbogdala/fizzle/blob/master/examples/lights_forward.go) present only a point light. 

Thx!

**Comment by tbogdala** [comment]
The light in the cube example is a directional light. 

https://github.com/tbogdala/fizzle/blob/master/examples/cube.go

If you look at the diffuse fragment shader, you'll see the part in the CalcADSLights() function that determines the behavior. If light.direction is not set then it makes a positional light; otherwise it just uses the direction.

https://github.com/tbogdala/fizzle/blob/master/examples/assets/forwardshaders/diffuse.fs

The lighting in the shaders is one of the major areas of the engine that need overhaul.

**Comment by sg3des** [comment]
adding to light _Direction_, no effect on shadows, i mean directional light with directional shadows. ^^

**Comment by tbogdala** [comment]
Oh yea, that.

Shadow support is pretty weak at the moment as well. If you look at the lights_forward.go example, you can see a block of code like this around line 162:

> // add light #1
> light := renderer.NewLight()
> light.Position = mgl.Vec3{5.0, 3.0, 5.0}
> light.DiffuseColor = mgl.Vec4{0.9, 0.9, 0.9, 1.0}
> light.DiffuseIntensity = 5.00
> light.AmbientIntensity = 0.20
> light.Attenuation = 0.2
> renderer.ActiveLights[0] = light
> light.CreateShadowMap(shadowTexSize, 0.5, 50.0, mgl.Vec3{-5.0, -3.0, -5.0})

Right now, CreateShadowMap takes a direction vector as the last parameter. You could always pass light.Direction. At some point I want to do something more than directional maps and maybe use a different projection other than orthographic. It's all very hardcoded proof-of-concept right now.
